//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab5.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Одиниці_виміру
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Одиниці_виміру()
        {
            this.Товари = new HashSet<Товари>();
        }
    
        public int Код_одиниці_виміру { get; set; }
        public string Одиниця_виміру { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Товари> Товари { get; set; }
    }
}
