//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab5.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товари
    {
        public int Артикул { get; set; }
        public Nullable<int> Код_одиниці_виміру { get; set; }
        public Nullable<int> Кількість { get; set; }
        public Nullable<decimal> Ціна { get; set; }
    
        public virtual Одиниці_виміру Одиниці_виміру { get; set; }
    }
}
